### ISSUE TITLE
Doesn't work with latest Facebook SDK v4.3.4

### ISSUE THREAD

**Issue by ghost** [fbsamples/friendsmash-unity#3]
I used Unity v4.2.2 with latest version of Facebook SDK v4.3.4 package. When I imported the package into the FriendSmash Unity project I got this error:
Assets/Scripts/MainMenu.cs(24,12): error CS0117: FB does not contain a definition for `GetAuthResponse'

It did worked with Facebook SDK v4.2.4 package.
